doc ///
   Key 
      MatroidComplexes
   Headline 
      Tools for computing the matroid chain complex
   Description
    Text
      The matroid complex generalizes Kontsevich's graph complex to matroids; see {\it Tatiana V. Alekseyevskaya, Alexandre V. Borovik: /. M. Gelfand, and Neil White, Matroid Homology (2000)}. 

      This package extends the Matroids package to compute the terms in the subcomplex generated by matroids of fixed rank $r$ in degree $\leq 9$, which can be used to form the entire complex.

      Rational coefficients are assumed: the matroid complex is generated by isomorphism classes of matroids which do not admit automorphisms acting as an odd permutation on the groundset. Elements with odd automorphisms have 2-torsion, and thus do not contribute to the ratinoal vector spaces.      

///


doc ///
   Key 
    withoutOddAut
    (withoutOddAut,Matroid)
   Headline
    Determines if a matroid admits an odd automorphism
   Usage
    withoutOddAut(M)
   Inputs
    M: Matroid
   Outputs
    : Boolean
   Description
    Text
      Calls getIsos(M,M) from the Matroids package and checks if there are no automorphisms which act as an odd permutation on the ground set. Ground set elements are labeled 
      $\{0,1,2,\dots,n-1\}$ as in the Matroids package. Returns true if no odd automorphisms exist, and false otherwise.
      
      Matroids which admit odd automorphisms vanish in the rational matroid complex. In the 
      example below, we ask whether the uniform matroids $U_{2,4}$ admits odd automorphisms. 
      That is, a matroid automorphism given by an odd permutation of its ground set $\{0,1,2,3\}.$
    Example
      M = uniformMatroid(2,4);
      withoutOddAut(M)

///
